# Generated by Django 4.0.4 on 2022-05-11 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Luz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('luz', models.CharField(max_length=45, verbose_name='Luz Necessária')),
            ],
            options={
                'verbose_name_plural': 'luzes',
                'db_table': 'luzes',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=45, unique=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=11)),
                ('url_imagem', models.CharField(blank=True, max_length=255)),
                ('tamanho_pote', models.IntegerField(verbose_name='Tamanho do Pote (cm)')),
                ('rega_necessaria', models.IntegerField(verbose_name='Rega Necessária (x por semana)')),
                ('toxica_animais', models.BooleanField(verbose_name='Tóxica para Animais?')),
                ('id_luz', models.ForeignKey(db_column='id_luz', on_delete=django.db.models.deletion.RESTRICT, to='website.luz')),
            ],
            options={
                'verbose_name_plural': 'produtos',
                'db_table': 'produtos',
            },
        ),
    ]
